name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: appservmaison-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: AppServMaison v${{ github.run_number }}
        draft: false
        prerelease: false
        body: |
          🏠 **AppServMaison - Contrôle Serveur Domestique**
          
          **Nouvelles fonctionnalités :**
          - Interface moderne avec onglets Serveur et Plex
          - Connexion automatique au démarrage
          - Design optimisé pour mobile
          
          **Installation :**
          1. Téléchargez `app-release.apk`
          2. Activez "Sources inconnues" sur Android
          3. Installez l'APK
          4. Configurez l'IP de votre serveur : `192.168.1.175:8080`
          
          **Serveur PowerShell requis :** Exécutez `serveur333-api-v2.ps1` en mode administrateur

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/vnd.android.package-archive